name: CD portofolio

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/web-portofolio
          git pull origin master
          git status
          npm run build
          pm2 status
          pm2 restart ${{ secrets.NAME_PM2 }}
          sudo nginx -t
          sudo nginx -s reload
